# Generated by Django 3.2.6 on 2021-08-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='comelete',
            new_name='complete',
        ),
    ]
